version: '3.1'

services:

  postgres:
    image: 'postgres'
    secrets:
      - postgres-user
      - postgres-password
    environment:
      restart: 'always'
      #POSTGRES_USER: 'postgres'
      #POSTGRES_PASSWORD: 'welcome1' # No need of it if using swarm secrets feature as below
      POSTGRES_DB: 'postgres'
      HOST: '0.0.0.0'
      PORT : '5432'
      TIMEZONE: 'UTC'
      POSTGRES_USER_FILE: /run/secrets/postgres-user      # using secrets from docker swarm
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password   # using secrets from docker swarm
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - polls_overlay

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'srbanala13@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'welcome1'
      PORT: '80'
    ports:
      - '80:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - polls_overlay

  django-polls:
    build: .
    image: anreddy/docker_compose_polls
    ports:
      - '8000:8000'
    depends_on: ["postgres"]
    networks:
      - polls_overlay



volumes:
  pg_data:
  pgadmin_data:

secrets:
  postgres-user:
    external: true
  postgres-password:
    external: true

networks:
  driver: overlay
   name: 'polls_overlay'
