# Generated by Django 2.0.7 on 2020-08-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monthly_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
