# Generated by Django 2.0.7 on 2020-08-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_auto_20200819_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthly_Expenses',
        ),
    ]
