# Generated by Django 2.0.7 on 2020-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_monthly_expenses_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
