# Generated by Django 2.0.7 on 2020-08-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0007_auto_20200822_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='monthly_payment',
            name='interest',
            field=models.FloatField(),
        ),
    ]
