# Generated by Django 2.0.7 on 2020-08-25 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0009_auto_20200825_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 16, 17, 23, 372676, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='monthly_expenses',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
