# Generated by Django 2.0.7 on 2020-12-27 22:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0010_auto_20200825_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabonacci_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 27, 22, 54, 29, 46050, tzinfo=utc)),
        ),
    ]
