# Generated by Django 2.0.7 on 2021-02-25 01:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0011_auto_20201227_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 25, 1, 5, 41, 77885, tzinfo=utc)),
        ),
    ]
