# Generated by Django 2.0.7 on 2021-02-25 14:30

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0012_auto_20210224_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='media_store',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='media_store',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 25, 14, 29, 37, 406840, tzinfo=utc)),
        ),
    ]
