# Generated by Django 2.0.7 on 2021-02-25 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0013_auto_20210225_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 25, 14, 58, 4, 269841, tzinfo=utc)),
        ),
    ]
