# Generated by Django 2.0.7 on 2021-08-20 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0016_auto_20210227_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 18, 36, 14, 731029, tzinfo=utc)),
        ),
    ]
