# Generated by Django 2.0.7 on 2021-10-04 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0019_auto_20211003_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 4, 19, 20, 59, 878160, tzinfo=utc)),
        ),
    ]
