# Generated by Django 2.0.7 on 2021-10-04 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0020_auto_20211004_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 4, 20, 46, 52, 16486, tzinfo=utc)),
        ),
    ]
