# Generated by Django 2.0.7 on 2021-10-05 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0022_auto_20211005_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_expenses',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 5, 15, 30, 32, 961310, tzinfo=utc)),
        ),
    ]
